### ISSUE TITLE
Missing inputs

### ISSUE THREAD

**Issue by lnroman** [SysBioChalmers/pcSecYeast#1]
Hello @feiranl ! @snmendoz talked with you yesterday, and we are running your script. 
There are some missing files.
Turnover worksheet is missing from tableS1, and is used in getkdeg.m. Maybe it is called kdeg now?
TargetProtein.xlsx is missing
blastp_res.xlsx is missing 
Proteome_collected.xlsx is missing
amylase_fpkm_Huang_NC.xlsx

Could you upload these files, please?

thank you in advance!

**Comment by feiranl** [comment]
Hi @lnroman, sorry for the late reply. Thanks for pointing this out! I have updated all files in this repository and removed the dependency for amylase_fpkm_Huang_NC.xlsx.
